import { api } from "../../lib/api";

export default async function AuditPage() {
  const events = await api.getAuditEvents();

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-2xl font-semibold">Audit Timeline</h1>
        <p className="text-sm text-slate-600">Structured events generated by every rotation phase.</p>
      </div>

      <div className="space-y-3">
        {events.map((event) => (
          <article key={event.id} className="rounded-xl border border-slate-200 bg-white p-4">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <p className="font-semibold text-slate-800">{event.eventType}</p>
              <p className="text-xs text-slate-500">{new Date(event.createdAt).toLocaleString()}</p>
            </div>
            <p className="mt-2 text-sm">{event.message}</p>
            <p className="mt-1 text-xs text-slate-500">Job: {event.jobId.slice(0, 12)}</p>
          </article>
        ))}
      </div>
    </div>
  );
}
