import { api } from "../../lib/api";

function formatJobLabel(jobId: string | null | undefined) {
  if (!jobId) {
    return "Job: n/a";
  }

  return `Job: ${jobId.slice(0, 12)}`;
}

export default async function AuditPage() {
  const events = await api.getAuditEvents();

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-semibold">Audit Timeline</h1>
        <p className="subtext">Structured events generated by every rotation phase.</p>
      </div>

      <div className="space-y-3">
        {events.map((event) => (
          <article key={event.id} className="panel p-4">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <p className="font-semibold text-slate-800">{event.eventType}</p>
              <p className="text-xs text-slate-500">{new Date(event.createdAt).toLocaleString()}</p>
            </div>
            <p className="mt-2 text-sm">{event.message}</p>
            <p className="mt-1 text-xs text-slate-500">{formatJobLabel(event.jobId)}</p>
          </article>
        ))}
      </div>
    </div>
  );
}
